"""Deterministic agent runner -- the spine's credential-free default.

This is what makes the conformance suite an honest proof: it exercises the whole
DAG / worktree / patch-barrier machinery with zero credentials and zero
nondeterminism, so a green conformance run means *the framework* works.

It is explicitly **not** an agent proof. Real agent integration is proven by the
opt-in smoke suite with `--runner copilot-sdk`.

Behaviour: for each file in ``node['writeSet']`` it writes deterministic content
derived from the node id and the file path. Fixtures in ``tests/fixtures/fake/``
override the generated content when a matching file exists, which lets tests
drive realistic scenarios (including failures) without an LLM.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

from adlc.config import Config
from adlc.ports import TaskNode, TaskOutcome

_FIXTURE_ENV = "ADLC_FAKE_FIXTURES"
_FAIL_MARKER = "adlc-fake-fail"


class FakeAgentRunner:
    name = "fake"
    kind = "agents"

    @staticmethod
    def detect(cfg: Config) -> tuple[bool, str]:
        return True, "built-in deterministic runner (no credentials required)"

    async def run_task(self, node: TaskNode, worktree: Path, cfg: Config) -> TaskOutcome:
        await asyncio.sleep(0)  # yield so concurrency is observable in timings

        node_id = node.get("id", "T000")
        title = node.get("title", "")

        if _FAIL_MARKER in title:
            return {
                "status": "fail",
                "log": f"fake runner: node '{node_id}' requested failure via title marker",
                "tokensIn": 0, "tokensOut": 0, "cost": 0.0,
            }

        fixture_root = Path(cfg.raw.get(_FIXTURE_ENV, "")) if cfg.raw.get(_FIXTURE_ENV) else None
        written: list[str] = []

        for rel_path in node.get("writeSet") or []:
            target = worktree / rel_path
            target.parent.mkdir(parents=True, exist_ok=True)

            content: str | None = None
            if fixture_root:
                candidate = fixture_root / node_id / rel_path
                if candidate.is_file():
                    content = candidate.read_text(encoding="utf-8")
            if content is None:
                content = _synthesise(node, rel_path)

            target.write_text(content, encoding="utf-8")
            written.append(rel_path)

        return {
            "status": "ok",
            "log": f"fake runner wrote {len(written)} file(s) for {node_id}",
            "tokensIn": 0, "tokensOut": 0, "cost": 0.0,
        }


def _synthesise(node: TaskNode, rel_path: str) -> str:
    """Deterministic, syntactically plausible content for the given path."""
    node_id = node.get("id", "T000")
    title = node.get("title", "")
    acceptance = ", ".join(node.get("acceptance") or []) or "none declared"
    suffix = Path(rel_path).suffix

    if suffix in {".py"}:
        return (
            f'"""{title}\n\nGenerated by the ADLC deterministic runner for {node_id}.\n'
            f'Acceptance: {acceptance}\n"""\n\n'
            f"ADLC_NODE = {node_id!r}\n\n\n"
            f"def placeholder() -> str:\n    return {node_id!r}\n"
        )
    if suffix in {".ts", ".js", ".tsx", ".jsx"}:
        return (
            f"// {title}\n// Generated by the ADLC deterministic runner for {node_id}.\n"
            f"// Acceptance: {acceptance}\n\n"
            f"export const ADLC_NODE = {node_id!r};\n"
        )
    if suffix in {".json"}:
        return f'{{\n  "adlcNode": "{node_id}",\n  "title": "{title}"\n}}\n'
    if suffix in {".md"}:
        return f"# {title or node_id}\n\nGenerated by the ADLC deterministic runner.\n\nAcceptance: {acceptance}\n"
    return f"{node_id}: {title}\n"
