"""Enrichment stage -- minimal knowledge facets, plus optional richer generators.

The spine ships the smallest honest set: one Gherkin feature, one rubric, one
benchmarks file. Workstream L9 adds diagrams, personas and wireframes by
exposing ``generate(run_dir, spec_text, cfg) -> list[Path]``; we call those
opportunistically and never let one failing generator break a run.
"""

from __future__ import annotations

import importlib
import re
from pathlib import Path
from typing import Any

import yaml

from adlc.config import Config
from adlc.runs import RunDir, utcnow

#: Optional generators contributed by leaf workstreams.
OPTIONAL_GENERATORS = (
    "adlc.stages.enrich_diagrams",
    "adlc.stages.enrich_personas",
    "adlc.stages.enrich_wireframe",
)

FEATURE_TEMPLATE = """Feature: {title}

  # Generated by ADLC from the specification. Scenario ids match the
  # acceptance criteria ids in spec.md so evidence can be traced back.

  Scenario: US1-AC1 Feature is reachable
    Given the application is running
    When a user navigates to the documented entry point
    Then the feature is available

  Scenario: US1-AC2 Primary flow completes
    Given the feature is available
    When the user completes the primary flow
    Then no error is reported

  Scenario: US1-AC3 Change is covered by tests
    Given the repository test suite
    When the suite runs
    Then it exercises the new behaviour and passes
"""

DEFAULT_RUBRIC: dict[str, Any] = {
    "id": "adlc-default",
    "description": "Minimum bar for a candidate implementation.",
    "threshold": 0.7,
    "criteria": [
        {
            "id": "R-spec-01",
            "statement": "A specification exists for this change.",
            "weight": 1,
            "kind": "deterministic",
            "check": {"type": "file_exists", "target": "spec/spec.md"},
            "acceptanceRefs": ["US1-AC1"],
        },
        {
            "id": "R-tests-01",
            "statement": "Acceptance scenarios are expressed as executable criteria.",
            "weight": 1,
            "kind": "deterministic",
            "check": {"type": "file_exists", "target": "enrichment/features/acceptance.feature"},
            "acceptanceRefs": ["US1-AC3"],
        },
        {
            "id": "R-evidence-01",
            "statement": "A replayable trace was captured for the candidate.",
            "weight": 2,
            "kind": "deterministic",
            "check": {"type": "file_exists", "target": "evidence/candidate-a/trace.zip"},
            "acceptanceRefs": ["US1-AC2"],
        },
    ],
}

DEFAULT_BENCHMARKS: dict[str, Any] = {
    "metrics": [
        {"id": "lcp_ms", "collector": "lighthouse", "budget": 2500, "direction": "lower_is_better"},
        {"id": "a11y_critical_violations", "collector": "axe", "budget": 0, "direction": "lower_is_better"},
        {"id": "console_errors", "collector": "playwright", "budget": 0, "direction": "lower_is_better"},
    ]
}


def _title(spec_text: str) -> str:
    for line in spec_text.splitlines():
        if line.startswith("# "):
            return re.sub(r"^#\s*(Feature Specification:)?\s*", "", line).strip()
    return "Change"


def run_enrich(cfg: Config, rd: RunDir) -> dict[str, Any]:
    started = utcnow()
    spec_path = rd.spec_dir / "spec.md"
    spec_text = spec_path.read_text(encoding="utf-8") if spec_path.is_file() else ""
    title = _title(spec_text)

    rd.enrichment_dir.mkdir(parents=True, exist_ok=True)
    (rd.enrichment_dir / "features").mkdir(parents=True, exist_ok=True)

    outputs: list[str] = []

    feature = rd.enrichment_dir / "features" / "acceptance.feature"
    feature.write_text(FEATURE_TEMPLATE.format(title=title), encoding="utf-8")
    outputs.append(rd.rel(feature))

    rubric = rd.enrichment_dir / "rubric.yaml"
    rubric.write_text(yaml.safe_dump(DEFAULT_RUBRIC, sort_keys=False), encoding="utf-8")
    outputs.append(rd.rel(rubric))

    benchmarks = rd.enrichment_dir / "benchmarks.yaml"
    benchmarks.write_text(yaml.safe_dump(DEFAULT_BENCHMARKS, sort_keys=False), encoding="utf-8")
    outputs.append(rd.rel(benchmarks))

    optional: dict[str, Any] = {}
    for module_name in OPTIONAL_GENERATORS:
        short = module_name.rsplit(".", 1)[-1]
        try:
            module = importlib.import_module(module_name)
        except ImportError:
            optional[short] = "not installed"
            continue
        try:
            produced = module.generate(rd.path, spec_text, cfg) or []
            paths = [rd.rel(Path(p)) for p in produced]
            outputs.extend(paths)
            optional[short] = paths or "produced nothing"
        except Exception as exc:  # noqa: BLE001 - one generator must not break the run
            optional[short] = f"failed: {type(exc).__name__}: {exc}"

    rd.write_stage(
        "enrich",
        outputs=outputs,
        message=f"{len(outputs)} enrichment artifact(s) for '{title}'",
        data={"title": title, "optionalGenerators": optional},
        started_at=started,
    )
    return {"title": title, "outputs": outputs, "optional": optional}
