"""Package ``adlc hotfix`` as a Microsoft Foundry hosted agent (``daytwo`` adapter).

Read this before believing anything about this module
-----------------------------------------------------
This is a **substitution, not a product integration.**

We looked for a Microsoft Foundry "SWE agent" SKU — something that would take an
incident and produce a code fix — and did not find one documented. Being precise
about that: we searched the Foundry agents documentation (including
``agent-yaml-reference`` and the Foundry agents overview) and general web search
on 2026-08-19 and found **no product by that or a similar name**. We could not
find documentation asserting that such a product does *not* exist either, so
treat "there is no Foundry SWE-agent SKU" as **UNVERIFIED as a negative claim**.
What is true and checkable is the positive statement: *we found none, so we
substituted our own.*

The substitution is: run **our** ``adlc hotfix`` CLI in a container, with
rubrics generated by ASSERT from the incident. The fix is produced by the
ordinary ADLC pipeline, gated by the ordinary ADLC gates. Foundry supplies
hosting and identity — nothing more.

What is verified (2026-08-19)
-----------------------------
From https://learn.microsoft.com/en-us/azure/foundry/agents/concepts/azure-yaml-reference
(the **current** format) and .../concepts/agent-yaml-reference (the deprecated one):

* "Hosted agent" **is** a real, documented Foundry concept: a containerised
  agent, ``kind: hosted``, built from source (``language: docker``) or run from
  a prebuilt ``image:``.
* **The current format is ``azure.yaml``.** The ``agent-yaml-reference`` page
  states that ``agent.manifest.yaml`` and ``agent.yaml`` are deprecated, and
  that as of the Foundry ``azd`` extension ``azure.ai.agents`` 1.0.0-beta.1 all
  hosted-agent configuration lives in a single ``azure.yaml``.
* ``azure.yaml`` top-level keys: ``name`` (required), ``services`` (required),
  ``requiredVersions``, ``metadata``, ``infra``. There is **no** top-level
  ``agents:``, ``ai:`` or ``resources:`` key — an agent is a service with
  ``host: azure.ai.agent``.
* ``azure.ai.agent`` service fields include: ``host``, ``kind``, ``name``,
  ``displayName``, ``description``, ``project``, ``language``, ``uses``,
  ``protocols``, ``env``, ``container``, ``startupCommand``, ``toolboxes``,
  ``image``, ``metadata``, ``agentCard``, ``policies``, ``memoryStores``,
  ``agentEndpoint``, ``codeConfiguration``.
* ``container.resources``: ``cpu`` from ``"0.25"`` to ``"4.0"``, ``memory``
  from ``0.5Gi`` to ``8.0Gi``.
* ``protocols`` is an array of ``{protocol, version}``. Valid protocol values:
  ``responses``, ``invocations``, ``a2a``, ``invocations_ws``, ``activity``.
* ``FOUNDRY_PROJECT_ENDPOINT`` is **injected by the platform** and must not be
  declared in ``env``: the docs reserve the ``FOUNDRY_`` and ``AGENT_``
  prefixes and warn that declaring it risks shadowing the platform value.
* Renames from the deprecated format: ``environment_variables`` (array of
  ``{name, value}``) → ``env`` (flat map); ``resources`` → nested under
  ``container``; ``language`` and ``project`` are new.
* Documented ``azd`` commands: ``azd ai agent init`` (``-m`` reads a manifest),
  ``azd ai agent run``, ``azd up``.

We therefore emit **``azure.yaml``** by default. The deprecated ``agent.yaml``
manifest shape is still available via :meth:`FoundryHotfixAgent.agent_manifest`
for anyone pinned to an older extension, and is labelled as deprecated wherever
it appears.

The honest gap: protocols
-------------------------
A hosted agent declares ``protocols`` — i.e. the container is expected to
**serve** that protocol over HTTP, and ``startupCommand`` is documented as "the
command that starts the agent **server**". ``adlc hotfix`` is a **command-line
program**; it serves nothing and exits when it is done. So the hosted form needs
a thin HTTP shim inside the image that speaks the declared protocol and shells
out to ``adlc hotfix``. **We do not ship that shim.**

Therefore the two forms of this substitution are not equally real:

===========================  ==========  =====================================
Form                         Status      Why
===========================  ==========  =====================================
Plain container job          **real**    ``adlc hotfix --incident F`` is the
                                         whole entrypoint. Runs anywhere a
                                         container runs, including an Azure
                                         Container Apps Job.
Foundry hosted agent         **example** Needs an unshipped protocol shim.
===========================  ==========  =====================================

Tier: **documented + disabled example** (``docs/PLAN.md`` §7).
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from adlc.config import Config

#: Injected by the Foundry platform for a hosted agent. Verified: it must NOT be
#: declared in ``environment_variables``. Its presence means we are the agent.
FOUNDRY_ENDPOINT_ENV = "FOUNDRY_PROJECT_ENDPOINT"

#: Accepted aliases for a Foundry/Azure AI project endpoint supplied by the
#: operator rather than the platform. Only ``FOUNDRY_PROJECT_ENDPOINT`` above is
#: documented by Microsoft; the rest are conventions we accept, not claims.
PROJECT_ENDPOINT_ENVS: tuple[str, ...] = (
    FOUNDRY_ENDPOINT_ENV, "AZURE_AI_PROJECT_ENDPOINT", "AZURE_AI_PROJECT_CONNECTION_STRING",
)

#: Standard ``azure-identity`` credential sources. These are the documented
#: ``EnvironmentCredential`` / managed-identity variables, not invented names.
CREDENTIAL_ENV_GROUPS: tuple[tuple[str, ...], ...] = (
    ("AZURE_TENANT_ID", "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET"),
    ("AZURE_TENANT_ID", "AZURE_CLIENT_ID", "AZURE_FEDERATED_TOKEN_FILE"),
    ("AZURE_TENANT_ID", "AZURE_CLIENT_ID", "AZURE_CLIENT_CERTIFICATE_PATH"),
    ("IDENTITY_ENDPOINT",),   # App Service / Container Apps managed identity
    ("MSI_ENDPOINT",),        # legacy managed identity
)

#: Where the container expects the incident payload to be mounted / written.
#: Ours, by convention — matches ``ADLC_INCIDENT_FILE`` in the sre_agent adapter.
DEFAULT_INCIDENT_PATH = "/var/adlc/incident.json"

#: Documented ``azd`` commands, quoted from the Foundry reference pages. Emitted
#: for humans to run; this adapter never executes them.
AZD_COMMANDS: tuple[str, ...] = (
    "azd ai agent init",
    "azd ai agent run",
    "azd up",
)

#: Valid ``protocols[].protocol`` values, verified on the azure.yaml reference.
VALID_PROTOCOLS: tuple[str, ...] = (
    "responses", "invocations", "a2a", "invocations_ws", "activity",
)

#: Everything about this integration that is example-only or unverified.
#: Surfaced programmatically so it cannot be lost when the docs are skimmed.
CAVEATS: tuple[str, ...] = (
    ("SUBSTITUTION: no Microsoft Foundry 'SWE agent' SKU was found in the docs we "
     "searched (2026-08-19); this runs our own `adlc hotfix` CLI instead. The "
     "non-existence of such a product is UNVERIFIED as a negative claim - we found "
     "no page asserting it either way."),
    ("PROTOCOL SHIM NOT SHIPPED: a hosted agent must serve its declared `protocols` "
     "over HTTP, and `startupCommand` is documented as the command that starts the "
     "agent *server*. `adlc hotfix` is a CLI that exits when done. Running this as a "
     "hosted agent requires an HTTP shim in the image that ADLC does not provide."),
    ("REAL ALTERNATIVE: the plain container-job form (entrypoint "
     "`adlc hotfix --incident FILE`) needs no shim and is the supported path."),
    ("FORMAT: azure.yaml is current. agent.yaml / agent.manifest.yaml are documented "
     "as deprecated as of the azure.ai.agents 1.0.0-beta.1 azd extension; "
     "FoundryHotfixAgent.agent_manifest() still renders that older shape."),
)


class FoundryHotfixAgent:
    """Describe ``adlc hotfix`` as a Foundry hosted agent / container job.

    Deliberately inert: it renders definitions and returns command lines. It
    never calls Azure, never deploys, never executes ``azd``. Deployment is a
    human action against a subscription — see ``examples/azure/``.
    """

    name = "foundry"
    kind = "daytwo"

    #: Publicly readable so callers can surface the honesty caveats verbatim.
    caveats = CAVEATS

    def __init__(self, agent_name: str = "adlc-hotfix", incident_path: str = DEFAULT_INCIDENT_PATH):
        self.agent_name = agent_name
        self.incident_path = incident_path

    # -- Adapter protocol -------------------------------------------------

    @staticmethod
    def detect(cfg: Config) -> tuple[bool, str]:
        """Cheap, non-raising, no network.

        Environment only: a project endpoint **and** a credential source. Being
        able to *describe* the agent is not the same as being able to use it, so
        we require both before claiming availability.
        """
        try:
            endpoint = next(
                (name for name in PROJECT_ENDPOINT_ENVS
                 if (os.environ.get(name) or "").strip()),
                None,
            )
            if endpoint is None:
                return False, (
                    "no Foundry project endpoint in the environment (looked for "
                    f"{', '.join(PROJECT_ENDPOINT_ENVS)}) - this adapter is an "
                    "example that requires an Azure subscription"
                )
            credential = next(
                (group for group in CREDENTIAL_ENV_GROUPS
                 if all((os.environ.get(var) or "").strip() for var in group)),
                None,
            )
            if credential is None:
                return False, (
                    f"{endpoint} is set but no Azure credential source is present "
                    "(expected AZURE_TENANT_ID + AZURE_CLIENT_ID + one of "
                    "AZURE_CLIENT_SECRET / AZURE_FEDERATED_TOKEN_FILE / "
                    "AZURE_CLIENT_CERTIFICATE_PATH, or a managed-identity "
                    "IDENTITY_ENDPOINT)"
                )
            return True, (
                f"{endpoint} is set with an Azure credential source ({'+'.join(credential)}); "
                "note the hosted-agent form still requires an HTTP protocol shim that ADLC "
                "does not ship - see FoundryHotfixAgent.caveats"
            )
        except Exception as exc:  # noqa: BLE001 - detect() must never raise
            return False, f"Foundry environment probe failed: {exc}"

    # -- Definition rendering ---------------------------------------------

    def container_command(self, incident_path: str | None = None) -> list[str]:
        """The container entrypoint. This part is real and needs no Azure."""
        return ["adlc", "hotfix", "--incident", incident_path or self.incident_path]

    def agent_service(
        self,
        *,
        image: str | None = None,
        project: str | None = "src/adlc-hotfix",
        cpu: str = "1.0",
        memory: str = "2.0Gi",
        protocol: str = "invocations",
        protocol_version: str = "2.0.0",
        project_service: str = "ai-project",
    ) -> dict[str, Any]:
        """The ``azure.ai.agent`` service block — the **current** format.

        Field names are those documented on the ``azure.yaml`` reference page.
        ``FOUNDRY_PROJECT_ENDPOINT`` is deliberately absent from ``env``: the
        platform injects it and the docs warn that declaring it shadows the
        platform value.

        Either ``image`` (prebuilt, e.g. from ACR) or ``project`` +
        ``language: docker`` (build from source) is used, not both.
        """
        if protocol not in VALID_PROTOCOLS:
            raise ValueError(
                f"protocol {protocol!r} is not one of the documented values "
                f"{VALID_PROTOCOLS}"
            )
        service: dict[str, Any] = {
            "host": "azure.ai.agent",
            "kind": "hosted",
            "name": self.agent_name,
            "displayName": "ADLC hotfix",
            "description": (
                "Runs the ADLC hotfix pipeline (adlc hotfix --incident FILE) against an "
                "incident raised by Azure SRE Agent."
            ),
            "uses": [project_service],
            "protocols": [{"protocol": protocol, "version": protocol_version}],
            "env": {
                "ADLC_INCIDENT_FILE": self.incident_path,
                "ADLC_PROFILE": "${ADLC_PROFILE}",
                "GITHUB_REPOSITORY": "${GITHUB_REPOSITORY}",
                "GITHUB_TOKEN": "${GITHUB_TOKEN}",
                "APPLICATIONINSIGHTS_CONNECTION_STRING":
                    "${APPLICATIONINSIGHTS_CONNECTION_STRING}",
            },
            "container": {"resources": {"cpu": cpu, "memory": memory}},
            "metadata": {
                "adlc.stage": "hotfix",
                "adlc.tier": "documented-disabled-example",
                "adlc.docs": "docs/day2-operations.md",
            },
        }
        if image:
            service["image"] = image
        else:
            service["project"] = project
            service["language"] = "docker"
            # UNVERIFIED whether Foundry accepts a non-server startupCommand.
            # `adlc hotfix` exits; the docs describe this as starting a *server*.
            service["startupCommand"] = " ".join(self.container_command())
        return service

    def azure_yaml(
        self,
        *,
        project_name: str = "adlc-day2",
        project_service: str = "ai-project",
        **kwargs: Any,
    ) -> dict[str, Any]:
        """A complete ``azure.yaml`` containing the hotfix agent.

        Top-level shape (``name`` + ``services``) follows the documented
        reference; an agent is a service with ``host: azure.ai.agent``.
        """
        return {
            "name": project_name,
            "services": {
                project_service: {"host": "azure.ai.project"},
                self.agent_name: self.agent_service(project_service=project_service, **kwargs),
            },
        }

    def agent_manifest(self, **kwargs: Any) -> dict[str, Any]:
        """The **deprecated** ``agent.manifest.yaml`` shape.

        Kept only for anyone pinned to a pre-1.0.0-beta.1 ``azure.ai.agents``
        extension. Prefer :meth:`azure_yaml`. Field names are those documented
        on the (deprecated) ``agent.yaml`` reference page: ``environment_variables``
        as an array of ``{name, value}`` and ``resources`` directly on the
        ``ContainerAgent``, both of which moved in the current format.
        """
        image = kwargs.pop("image", "${ADLC_ACR_LOGIN_SERVER}/adlc-hotfix:${ADLC_IMAGE_TAG}")
        cpu = kwargs.pop("cpu", "1.0")
        memory = kwargs.pop("memory", "2.0Gi")
        protocol = kwargs.pop("protocol", "invocations")
        return {
            "name": self.agent_name,
            "description": (
                "DEPRECATED FORMAT. Runs the ADLC hotfix pipeline against an incident "
                "raised by Azure SRE Agent. Prefer azure.yaml."
            ),
            "metadata": {"adlc.stage": "hotfix", "adlc.format": "deprecated-agent.yaml"},
            "parameters": {
                "github_pat": {
                    "secret": True,
                    "description": "GitHub token with permission to push the hotfix branch "
                                   "and open a pull request.",
                },
            },
            "resources": [{"type": "foundry-project", "name": "${AZURE_AI_PROJECT_NAME}"}],
            "template": {
                "name": self.agent_name,
                "kind": "hosted",
                "protocols": [protocol],
                "image": image,
                "resources": {"cpu": cpu, "memory": memory},
                "environment_variables": [
                    {"name": "ADLC_INCIDENT_FILE", "value": self.incident_path},
                    {"name": "GITHUB_REPOSITORY", "value": "${GITHUB_REPOSITORY}"},
                    {"name": "GITHUB_TOKEN", "value": "${GITHUB_TOKEN}"},
                ],
            },
        }

    def render(self, out: Path | str, **kwargs: Any) -> Path:
        """Write the ``azure.yaml``, caveats included as a header comment."""
        out = Path(out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(self.render_yaml(**kwargs), encoding="utf-8")
        return out

    def render_yaml(self, **kwargs: Any) -> str:
        import yaml

        header = [
            "# DISABLED EXAMPLE - requires an Azure subscription. Nothing here is applied",
            "# by ADLC; `adlc doctor` reports this adapter unavailable without Azure env.",
            "#",
            *[f"# {line}" for caveat in CAVEATS for line in _wrap(caveat, 94)],
            "#",
            "# Documented azd commands (this file is not executed by ADLC):",
            *[f"#   {command}" for command in AZD_COMMANDS],
            "#",
            "# Container entrypoint (the part that is real):",
            f"#   {' '.join(self.container_command())}",
            "",
        ]
        body = yaml.safe_dump(self.azure_yaml(**kwargs), sort_keys=False, default_flow_style=False)
        return "\n".join(header) + body


def _wrap(text: str, width: int) -> list[str]:
    words, lines, current = text.split(), [], ""
    for word in words:
        if current and len(current) + len(word) + 1 > width:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        lines.append(current)
    return lines
