"""Accessibility evidence collector using ``@axe-core/playwright`` (L6).

Drives a real browser through Playwright, runs axe-core against each configured
URL, emits a redacted ``axe.json`` plus a normalised ``axe-measurements.json``.

Shared helpers (budget loading, redaction, measurement emission) live in
:mod:`adlc.adapters.evidence.lighthouse` -- see that module's docstring for why.

See ``docs/evidence.md``.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

from adlc.adapters.evidence.lighthouse import (
    MetricSpec,
    ToolResult,
    aggregate_values,
    artifact_ref,
    build_measurements,
    clear_previous,
    coerce_number,
    collector_options,
    find_executable,
    find_node_package,
    json_pointer,
    load_benchmarks,
    metrics_for,
    read_json,
    redact,
    resolve_run_dir,
    run_tool,
    safe_config,
    target_urls,
    timeout_for,
    write_json,
    write_measurement_files,
)
from adlc.ports import ArtifactRef, Run

if TYPE_CHECKING:  # pragma: no cover
    from adlc.config import Config

__all__ = ["AXE_IMPACTS", "SCAN_SCRIPT", "AxeCollector", "extract_axe"]

#: axe-core impact levels, most severe first.
AXE_IMPACTS: tuple[str, ...] = ("critical", "serious", "moderate", "minor")

#: Attacker-controlled markup is truncated before it lands in evidence.
MAX_HTML_SNIPPET = 512

DEFAULT_TAGS: tuple[str, ...] = ("wcag2a", "wcag2aa")

#: CommonJS on purpose: it resolves identically whether or not the nearest
#: package.json declares ``"type": "module"``, and it tolerates both the
#: ``default`` and bare-object export shapes of ``@axe-core/playwright``.
SCAN_SCRIPT = r"""// Generated by the ADLC L6 axe evidence collector. Do not edit by hand.
const fs = require('node:fs');
const path = require('node:path');

const configPath = process.argv[2];
const outPath = process.argv[3];
const cfg = JSON.parse(fs.readFileSync(configPath, 'utf8'));

const playwright = require('playwright');
const axeModule = require('@axe-core/playwright');
const AxeBuilder = axeModule.default || axeModule.AxeBuilder || axeModule;

(async () => {
  const engine = playwright[cfg.browser] || playwright.chromium;
  const results = [];
  const errors = [];
  let browser;
  try {
    browser = await engine.launch();
  } catch (err) {
    fs.writeFileSync(
      outPath,
      JSON.stringify({ results: [], errors: [{ url: null, message: String(err && err.message || err) }] }, null, 2)
    );
    process.exit(2);
  }
  for (const url of cfg.urls) {
    let context;
    try {
      context = await browser.newContext();
      const page = await context.newPage();
      await page.goto(url, { waitUntil: cfg.waitUntil, timeout: cfg.navigationTimeoutMs });
      let builder = new AxeBuilder({ page });
      if (cfg.tags && cfg.tags.length) builder = builder.withTags(cfg.tags);
      if (cfg.disableRules && cfg.disableRules.length) builder = builder.disableRules(cfg.disableRules);
      const result = await builder.analyze();
      result.url = result.url || url;
      results.push(result);
    } catch (err) {
      errors.push({ url, message: String((err && err.message) || err) });
    } finally {
      if (context) await context.close().catch(() => {});
    }
  }
  await browser.close().catch(() => {});
  fs.writeFileSync(outPath, JSON.stringify({ results, errors }, null, 2));
  process.exit(results.length ? 0 : 1);
})().catch((err) => {
  fs.writeFileSync(
    outPath,
    JSON.stringify({ results: [], errors: [{ url: null, message: String((err && err.message) || err) }] }, null, 2)
  );
  process.exit(2);
});
"""


def _violations(result: dict[str, Any]) -> list[dict[str, Any]]:
    raw = result.get("violations")
    return [v for v in raw if isinstance(v, dict)] if isinstance(raw, list) else []


def _count_by_impact(result: dict[str, Any], impact: str) -> float:
    return float(
        sum(1 for v in _violations(result) if str(v.get("impact") or "").lower() == impact)
    )


def _nodes_by_impact(result: dict[str, Any], impact: str | None) -> float:
    total = 0
    for violation in _violations(result):
        if impact is not None and str(violation.get("impact") or "").lower() != impact:
            continue
        nodes = violation.get("nodes")
        total += len(nodes) if isinstance(nodes, list) else 0
    return float(total)


def _length(result: dict[str, Any], key: str) -> float:
    value = result.get(key)
    return float(len(value)) if isinstance(value, list) else 0.0


#: metric id -> extractor over one axe-core results document.
AXE_CATALOGUE: dict[str, Any] = {
    "a11y_critical_violations": lambda r: _count_by_impact(r, "critical"),
    "a11y_serious_violations": lambda r: _count_by_impact(r, "serious"),
    "a11y_moderate_violations": lambda r: _count_by_impact(r, "moderate"),
    "a11y_minor_violations": lambda r: _count_by_impact(r, "minor"),
    "a11y_total_violations": lambda r: float(len(_violations(r))),
    "a11y_violation_nodes": lambda r: _nodes_by_impact(r, None),
    "a11y_critical_nodes": lambda r: _nodes_by_impact(r, "critical"),
    "a11y_serious_nodes": lambda r: _nodes_by_impact(r, "serious"),
    "a11y_blocking_violations": lambda r: _count_by_impact(r, "critical")
    + _count_by_impact(r, "serious"),
    "a11y_incomplete": lambda r: _length(r, "incomplete"),
    "a11y_passes": lambda r: _length(r, "passes"),
    "a11y_inapplicable": lambda r: _length(r, "inapplicable"),
}


def extract_axe(result: dict[str, Any], specs: list[MetricSpec]) -> dict[str, float | None]:
    """Map one axe-core results document onto ``{metricId: value | None}``.

    Violations whose ``impact`` is ``null`` are counted in totals but in none of
    the per-impact buckets -- axe reports an unknown impact and inventing one
    would be a fabricated measurement.
    """
    values: dict[str, float | None] = {}
    for spec in specs:
        metric_id = spec["id"]
        scale = spec.get("scale")
        pointer = spec.get("source")
        if pointer:
            raw = coerce_number(json_pointer(result, pointer))
        else:
            extractor = AXE_CATALOGUE.get(metric_id)
            raw = None if extractor is None else coerce_number(extractor(result))
        values[metric_id] = None if raw is None else raw * float(scale if scale is not None else 1)
    return values


def _truncate_html(node: Any, depth: int = 0) -> Any:
    """Clip ``html`` snippets. axe echoes page markup verbatim; it is
    attacker-controlled and can embed CSRF/session values."""
    if depth > 32:
        return node
    if isinstance(node, dict):
        out: dict[str, Any] = {}
        for key, value in node.items():
            if key == "html" and isinstance(value, str) and len(value) > MAX_HTML_SNIPPET:
                out[key] = value[:MAX_HTML_SNIPPET] + "… [truncated]"
            else:
                out[key] = _truncate_html(value, depth + 1)
        return out
    if isinstance(node, list):
        return [_truncate_html(item, depth + 1) for item in node]
    return node


class AxeCollector:
    """axe-core accessibility evidence collector.

    Requires Node plus the ``@axe-core/playwright`` and ``playwright`` packages.
    Optional: with them absent the spine's Playwright collector alone still
    satisfies the credential-free conformance suite.
    """

    name = "axe"
    kind = "evidence"

    #: Outputs owned by this collector, cleared before every attempt.
    OUTPUTS = (
        "axe.json",
        "axe-[0-9]*.json",
        "axe-measurements.json",
        "axe-unmeasured.json",
        "axe-scan.cjs",
        "axe-scan.config.json",
        "axe-scan.raw.json",
    )

    INSTALL_HINT = (
        "install with `npm i -D @axe-core/playwright playwright` "
        "then `npx playwright install chromium`"
    )

    @staticmethod
    def detect(cfg: Config) -> tuple[bool, str]:
        try:
            node = find_executable("node", cfg)
            if node is None:
                return False, "node not on PATH — install Node.js 18+ from https://nodejs.org"
            if find_executable("npx", cfg) is None:
                return False, "npx not on PATH — reinstall Node.js so npm/npx are available"
            missing = [
                pkg
                for pkg in ("@axe-core/playwright", "playwright")
                if find_node_package(pkg, cfg) is None
            ]
            if missing:
                return False, (
                    f"{', '.join(missing)} not installed — {AxeCollector.INSTALL_HINT}"
                )
        except Exception as exc:  # noqa: BLE001 - detect() must never raise
            return False, f"axe detection failed: {exc}"
        return True, f"node + @axe-core/playwright available ({node})"

    def collect(self, run: Run, variant: str, out: Path) -> list[ArtifactRef]:
        out = Path(out)
        out.mkdir(parents=True, exist_ok=True)
        clear_previous(out, self.OUTPUTS)
        run_dir = resolve_run_dir(run, out)
        cfg = safe_config(out)
        benchmarks = load_benchmarks(run_dir)
        specs = metrics_for(benchmarks, self.name)
        options = collector_options(benchmarks, self.name)
        urls = target_urls(benchmarks, self.name, run)

        artifacts: list[ArtifactRef] = []
        available, reason = self.detect(cfg)  # type: ignore[arg-type]
        if not available:
            return self._abort(run, variant, out, run_dir, specs, "tool_unavailable", reason)
        if not urls:
            return self._abort(
                run, variant, out, run_dir, specs, "output_missing",
                "no target URL configured — set target.url in benchmarks.yaml "
                "or the ADLC_TARGET_URL environment variable",
            )

        timeout = timeout_for(benchmarks, self.name, default=300)
        script_path = out / "axe-scan.cjs"
        script_path.write_text(SCAN_SCRIPT, encoding="utf-8")
        config_path = write_json(
            out / "axe-scan.config.json",
            redact(
                {
                    "urls": urls,
                    "tags": self._tags(options),
                    "disableRules": [
                        str(r) for r in options.get("disableRules", []) if str(r).strip()
                    ],
                    "browser": str(options.get("browser") or "chromium"),
                    "waitUntil": str(options.get("waitUntil") or "load"),
                    "navigationTimeoutMs": max(1, timeout) * 1000,
                }
            ),
        )
        artifacts.append(artifact_ref(script_path, run_dir, "axe_script", "text/javascript"))
        artifacts.append(artifact_ref(config_path, run_dir, "axe_config", "application/json"))
        raw_path = out / "axe-scan.raw.json"

        node = find_executable("node", cfg) or "node"
        env: dict[str, str] = {}
        modules = find_node_package("@axe-core/playwright", cfg)
        if modules is not None:
            env["NODE_PATH"] = str(modules)
        tool = run_tool(
            [node, str(script_path), str(config_path), str(raw_path)],
            cwd=out,
            timeout=timeout,
            env=env,
        )

        payload = read_json(raw_path)
        results = payload.get("results") if isinstance(payload, dict) else None
        scan_errors = payload.get("errors") if isinstance(payload, dict) else None
        results = [r for r in results if isinstance(r, dict)] if isinstance(results, list) else []
        wrote_something = raw_path.exists()
        raw_path.unlink(missing_ok=True)

        if not results:
            cause = tool.get("cause") or (
                "output_unreadable" if wrote_something else "output_missing"
            )
            detail = tool.get("reason") or (
                "the axe scan returned no results document"
                if wrote_something
                else "node wrote no axe results document"
            )
            if isinstance(scan_errors, list) and scan_errors:
                first = scan_errors[0]
                if isinstance(first, dict) and first.get("message"):
                    detail = f"{detail}: {first['message']}"
            return self._abort(run, variant, out, run_dir, specs, cause, detail, artifacts, tool)

        report_paths: list[Path] = []
        for index, result in enumerate(results):
            target = out / ("axe.json" if index == 0 else f"axe-{index}.json")
            report_paths.append(write_json(target, redact(_truncate_html(result))))
        primary = artifact_ref(report_paths[0], run_dir, "axe", "application/json")
        artifacts.append(primary)
        for extra in report_paths[1:]:
            artifacts.append(artifact_ref(extra, run_dir, "axe", "application/json"))

        per_url = [extract_axe(result, specs) for result in results]
        values: dict[str, float | None] = {}
        reasons: dict[str, tuple[str, str]] = {}
        for spec in specs:
            found = [v for v in (page.get(spec["id"]) for page in per_url) if v is not None]
            values[spec["id"]] = aggregate_values(found, spec)
            if not found and not spec.get("source") and spec["id"] not in AXE_CATALOGUE:
                reasons[spec["id"]] = (
                    "metric_unmapped",
                    (
                        f"'{spec['id']}' is not a known axe metric — declare a `source` "
                        "JSON Pointer in benchmarks.yaml"
                    ),
                )
        measurements, unmeasured = build_measurements(
            specs, values, self.name, primary["sha256"], reasons,
        )
        if isinstance(scan_errors, list) and scan_errors:
            tool = {**tool, "scanErrors": redact(scan_errors)}
        for path in write_measurement_files(
            out, self.name, run, variant, tool, measurements, unmeasured
        ):
            artifacts.append(
                artifact_ref(path, run_dir, "evidence_measurements", "application/json")
            )
        return artifacts

    # -- helpers ---------------------------------------------------------

    def _tags(self, options: dict[str, Any]) -> list[str]:
        tags = options.get("tags")
        if isinstance(tags, str):
            tags = [tags]
        if isinstance(tags, list):
            cleaned = [str(t).strip() for t in tags if str(t).strip()]
            if cleaned:
                return cleaned
        return list(DEFAULT_TAGS)

    def _abort(
        self,
        run: Run,
        variant: str,
        out: Path,
        run_dir: Path | None,
        specs: list[MetricSpec],
        cause: str,
        reason: str,
        artifacts: list[ArtifactRef] | None = None,
        tool: ToolResult | None = None,
    ) -> list[ArtifactRef]:
        """Record why nothing was measured. Emits no values, ever."""
        result: list[ArtifactRef] = list(artifacts or [])
        if not specs:
            return result
        _, unmeasured = build_measurements(
            specs, {}, self.name, "", {}, default_reason=(cause, reason),
        )
        info: ToolResult = tool or {"ran": False, "cause": cause, "reason": reason}
        for path in write_measurement_files(out, self.name, run, variant, info, [], unmeasured):
            result.append(artifact_ref(path, run_dir, "evidence_measurements", "application/json"))
        return result
