"""k6 load / performance evidence collector (L6).

Runs ``k6 run --summary-export`` against the candidate build, emits a redacted
``k6.json`` plus a normalised ``k6-measurements.json``.

Shared helpers (budget loading, redaction, measurement emission) live in
:mod:`adlc.adapters.evidence.lighthouse` -- see that module's docstring for why.

See ``docs/evidence.md``.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

from adlc.adapters.evidence.lighthouse import (
    MetricSpec,
    ToolResult,
    aggregate_values,
    artifact_ref,
    build_measurements,
    clear_previous,
    coerce_number,
    collector_options,
    find_executable,
    json_pointer,
    load_benchmarks,
    metrics_for,
    read_json,
    redact,
    resolve_run_dir,
    run_tool,
    safe_config,
    target_urls,
    timeout_for,
    write_json,
    write_measurement_files,
)
from adlc.ports import ArtifactRef, Run

if TYPE_CHECKING:  # pragma: no cover
    from adlc.config import Config

__all__ = ["K6_CATALOGUE", "K6Collector", "extract_k6", "render_script"]

#: metric id -> (JSON Pointer into the k6 summary export, multiplier)
K6_CATALOGUE: dict[str, tuple[str, float]] = {
    "p50_latency_ms": ("/metrics/http_req_duration/med", 1.0),
    "p90_latency_ms": ("/metrics/http_req_duration/p(90)", 1.0),
    "p95_latency_ms": ("/metrics/http_req_duration/p(95)", 1.0),
    "p99_latency_ms": ("/metrics/http_req_duration/p(99)", 1.0),
    "avg_latency_ms": ("/metrics/http_req_duration/avg", 1.0),
    "min_latency_ms": ("/metrics/http_req_duration/min", 1.0),
    "max_latency_ms": ("/metrics/http_req_duration/max", 1.0),
    "p95_wait_ms": ("/metrics/http_req_waiting/p(95)", 1.0),
    "p95_connect_ms": ("/metrics/http_req_connecting/p(95)", 1.0),
    "rps": ("/metrics/http_reqs/rate", 1.0),
    "requests_total": ("/metrics/http_reqs/count", 1.0),
    "error_rate": ("/metrics/http_req_failed/value", 1.0),
    "error_rate_pct": ("/metrics/http_req_failed/value", 100.0),
    "failed_requests": ("/metrics/http_req_failed/fails", 1.0),
    "checks_failed": ("/metrics/checks/fails", 1.0),
    "checks_passed": ("/metrics/checks/passes", 1.0),
    "check_pass_rate": ("/metrics/checks/value", 1.0),
    "iterations": ("/metrics/iterations/count", 1.0),
    "iteration_rate": ("/metrics/iterations/rate", 1.0),
    "data_received_kb": ("/metrics/data_received/count", 1 / 1024),
    "data_sent_kb": ("/metrics/data_sent/count", 1 / 1024),
    "vus_max": ("/metrics/vus_max/max", 1.0),
}

#: Trend statistics requested from k6 so the p95/p99 pointers above resolve.
TREND_STATS = "avg,min,med,max,p(90),p(95),p(99)"

SCRIPT_TEMPLATE = """// Generated by ADLC L6 k6 evidence collector. Do not edit by hand.
// Regenerated on every run from runs/<run-id>/enrichment/benchmarks.yaml.
import http from 'k6/http';
import {{ check, sleep }} from 'k6';

export const options = {{
  vus: {vus},
  duration: '{duration}',
  // Thresholds are advisory here: ADLC compares measured values against
  // benchmarks.yaml itself so that a missing metric can never pass silently.
  thresholds: {{
    http_req_failed: [{{ threshold: 'rate<1', abortOnFail: false }}],
  }},
}};

const TARGET = __ENV.ADLC_TARGET_URL || {target!r};

export default function () {{
  const res = http.get(TARGET);
  check(res, {{
    'status is 2xx or 3xx': (r) => r.status >= 200 && r.status < 400,
  }});
  sleep(1);
}}
"""


def render_script(target: str, vus: int, duration: str) -> str:
    """Render the default constant-VU GET script."""
    return SCRIPT_TEMPLATE.format(vus=max(1, int(vus)), duration=duration, target=target)


def extract_k6(summary: dict[str, Any], specs: list[MetricSpec]) -> dict[str, float | None]:
    """Map a k6 ``--summary-export`` document onto ``{metricId: value | None}``."""
    values: dict[str, float | None] = {}
    for spec in specs:
        metric_id = spec["id"]
        pointer = spec.get("source")
        scale = spec.get("scale")
        if not pointer:
            entry = K6_CATALOGUE.get(metric_id)
            if entry is None:
                values[metric_id] = None
                continue
            pointer, catalogue_scale = entry
            scale = catalogue_scale if scale is None else scale
        raw = coerce_number(json_pointer(summary, pointer))
        values[metric_id] = None if raw is None else raw * float(scale if scale is not None else 1)
    return values


class K6Collector:
    """k6 load-test evidence collector.

    Requires the ``k6`` binary. Optional: with k6 absent the spine's Playwright
    collector alone still satisfies the credential-free conformance suite.
    """

    name = "k6"
    kind = "evidence"

    #: Outputs owned by this collector, cleared before every attempt.
    OUTPUTS = ("k6.json", "k6-script.js", "k6-measurements.json", "k6-unmeasured.json")

    INSTALL_HINT = "install from https://k6.io/docs/get-started/installation/"

    @staticmethod
    def detect(cfg: Config) -> tuple[bool, str]:
        try:
            exe = find_executable("k6", cfg)
        except Exception as exc:  # noqa: BLE001 - detect() must never raise
            return False, f"k6 detection failed: {exc}"
        if exe is None:
            return False, f"k6 not on PATH — {K6Collector.INSTALL_HINT}"
        return True, f"k6 available at {exe}"

    def collect(self, run: Run, variant: str, out: Path) -> list[ArtifactRef]:
        out = Path(out)
        out.mkdir(parents=True, exist_ok=True)
        clear_previous(out, self.OUTPUTS)
        run_dir = resolve_run_dir(run, out)
        cfg = safe_config(out)
        benchmarks = load_benchmarks(run_dir)
        specs = metrics_for(benchmarks, self.name)
        options = collector_options(benchmarks, self.name)

        artifacts: list[ArtifactRef] = []
        available, reason = self.detect(cfg)  # type: ignore[arg-type]
        if not available:
            return self._abort(run, variant, out, run_dir, specs, "tool_unavailable", reason)

        script_path, script_reason = self._resolve_script(
            benchmarks, options, out, run_dir, cfg, run
        )
        if script_path is None:
            return self._abort(run, variant, out, run_dir, specs, "output_missing", script_reason)
        artifacts.append(artifact_ref(script_path, run_dir, "k6_script", "text/javascript"))

        summary_path = out / "k6.json"
        exe = find_executable("k6", cfg) or "k6"
        command = [
            exe,
            "run",
            "--summary-export",
            str(summary_path),
            "--summary-trend-stats",
            TREND_STATS,
            "--no-usage-report",
        ]
        for key, value in (options.get("env") or {}).items():
            command.extend(["--env", f"{key}={value}"])
        command.extend(str(arg) for arg in options.get("extraArgs", []) if str(arg).strip())
        command.append(str(script_path))

        tool = run_tool(
            command,
            cwd=out,
            timeout=timeout_for(benchmarks, self.name),
            env={"K6_NO_USAGE_REPORT": "true"},
        )

        summary = read_json(summary_path)
        if not isinstance(summary, dict) or not summary.get("metrics"):
            wrote_something = summary_path.exists()
            cause = tool.get("cause") or (
                "output_unreadable" if wrote_something else "output_missing"
            )
            detail = tool.get("reason") or (
                "k6 --summary-export document carried no metrics"
                if wrote_something
                else "k6 wrote no --summary-export document"
            )
            summary_path.unlink(missing_ok=True)
            return self._abort(run, variant, out, run_dir, specs, cause, detail, artifacts, tool)

        # Rewrite the summary redacted: group/check names and tags can echo
        # request URLs that carry signed tokens.
        write_json(summary_path, redact(summary))
        summary_ref = artifact_ref(summary_path, run_dir, "k6", "application/json")
        artifacts.append(summary_ref)

        extracted = extract_k6(summary, specs)
        values: dict[str, float | None] = {}
        reasons: dict[str, tuple[str, str]] = {}
        for spec in specs:
            found = [v for v in (extracted.get(spec["id"]),) if v is not None]
            values[spec["id"]] = aggregate_values(found, spec)
            if not found and not spec.get("source") and spec["id"] not in K6_CATALOGUE:
                reasons[spec["id"]] = (
                    "metric_unmapped",
                    (
                        f"'{spec['id']}' is not a known k6 metric — declare a `source` "
                        "JSON Pointer in benchmarks.yaml"
                    ),
                )
        measurements, unmeasured = build_measurements(
            specs, values, self.name, summary_ref["sha256"], reasons,
        )
        for path in write_measurement_files(
            out, self.name, run, variant, tool, measurements, unmeasured
        ):
            artifacts.append(
                artifact_ref(path, run_dir, "evidence_measurements", "application/json")
            )
        return artifacts

    # -- helpers ---------------------------------------------------------

    def _resolve_script(
        self,
        benchmarks: dict[str, Any],
        options: dict[str, Any],
        out: Path,
        run_dir: Path | None,
        cfg: Config | None,
        run: Run | None = None,
    ) -> tuple[Path | None, str]:
        """Return an existing script, or generate one from the configured target."""
        declared = options.get("script")
        if isinstance(declared, str) and declared.strip():
            candidate = Path(declared.strip())
            roots = [p for p in (run_dir, getattr(cfg, "root", None), Path.cwd()) if p is not None]
            if candidate.is_absolute() and candidate.is_file():
                return candidate, ""
            for root in roots:
                resolved = Path(root) / candidate
                if resolved.is_file():
                    return resolved, ""
            return None, (
                f"k6 script '{declared}' not found relative to the run directory or repo root"
            )

        urls = target_urls(benchmarks, self.name, run)
        if not urls:
            return None, (
                "no k6 target configured — set collectors.k6.url, target.url in "
                "benchmarks.yaml, or the ADLC_TARGET_URL environment variable"
            )
        vus = int(coerce_number(options.get("vus")) or 5)
        duration = str(options.get("duration") or "30s")
        path = out / "k6-script.js"
        path.write_text(render_script(urls[0], vus, duration), encoding="utf-8")
        return path, ""

    def _abort(
        self,
        run: Run,
        variant: str,
        out: Path,
        run_dir: Path | None,
        specs: list[MetricSpec],
        cause: str,
        reason: str,
        artifacts: list[ArtifactRef] | None = None,
        tool: ToolResult | None = None,
    ) -> list[ArtifactRef]:
        """Record why nothing was measured. Emits no values, ever."""
        result: list[ArtifactRef] = list(artifacts or [])
        if not specs:
            return result
        _, unmeasured = build_measurements(
            specs, {}, self.name, "", {}, default_reason=(cause, reason),
        )
        info: ToolResult = tool or {"ran": False, "cause": cause, "reason": reason}
        for path in write_measurement_files(out, self.name, run, variant, info, [], unmeasured):
            result.append(artifact_ref(path, run_dir, "evidence_measurements", "application/json"))
        return result
