"""Frozen contracts for the ADLC framework.

Everything in this module is a **stable interface**. The spine ships a
credential-free default implementation for every Protocol; adapters registered
via ``pyproject.toml`` entry points are pure additions that can never block the
spine.

See ``docs/PLAN.md`` §4 for the authoritative contract description.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any, Literal, Protocol, TypedDict, runtime_checkable

if TYPE_CHECKING:  # pragma: no cover
    from adlc.config import Config

# ---------------------------------------------------------------------------
# Vocabulary
# ---------------------------------------------------------------------------

AdapterKind = Literal[
    "agents", "taskstore", "evals", "evidence",
    "flags", "telemetry", "gate", "daytwo", "export",
]

StageName = Literal[
    "intake", "qualify", "spec", "enrich", "graph", "build",
    "evidence", "evidence_diff", "persona_feedback", "eval", "gate",
    "complete", "report", "review", "feedback", "export",
]

RunStatus = Literal[
    "draft", "specced", "built", "evaluated",
    "gated", "reported", "decided", "abandoned",
]

GateStatus = Literal["pass", "fail", "not_run"]
Severity = Literal["low", "medium", "high", "critical"]
TaskKind = Literal["implement", "test", "doc", "infra"]
DecisionOutcome = Literal["ship", "do_not_ship", "iterate", "rerun"]

#: Capsule budgets (plan section 4.3). Hard caps -- enforced, not advisory.
CAPSULE_MAX_TOTAL_BYTES = 65_536
CAPSULE_MAX_FILE_BYTES = 8_192
CAPSULE_MAX_FILES = 12

#: Paths an agent-authored patch may never touch (plan section 4.8).
PROTECTED_PATHS: tuple[str, ...] = (
    ".github/**", ".adlc/**", "schemas/**", "docs/decisions/**", "pyproject.toml",
)

#: Gate ids known to the framework. `required` is resolved from config+profile.
GATE_IDS: tuple[str, ...] = (
    "tests", "secrets_local", "deps_local", "evidence_completeness",
    "security", "code_quality", "evals", "governance",
    "adversarial_review", "evidence_review", "pre_registration", "spec_coverage",
    "feature_completeness",
)


# ---------------------------------------------------------------------------
# Data shapes  (mirrored 1:1 by JSON Schemas in ``schemas/``)
# ---------------------------------------------------------------------------


class StageResult(TypedDict, total=False):
    """One immutable stage execution.

    Written to ``runs/<run>/stages/<stage>.<attempt>.json``. Never mutated.
    A re-run appends ``attempt: n+1``.
    """

    stage: str
    attempt: int
    status: Literal["ok", "fail", "skipped"]
    startedAt: str
    endedAt: str
    outputs: list[str]
    digest: str
    message: str
    data: dict[str, Any]


class ArtifactRef(TypedDict, total=False):
    path: str
    kind: str
    mimeType: str
    sha256: str
    bytes: int


class GateResult(TypedDict, total=False):
    id: str
    required: bool
    status: GateStatus
    severity: Severity
    observed: dict[str, Any]
    expected: dict[str, Any]
    message: str
    evidence: list[str]


class Variant(TypedDict, total=False):
    key: str
    role: Literal["control", "treatment"]
    commit: str
    flagKeys: list[str]


class Decision(TypedDict, total=False):
    outcome: DecisionOutcome
    rationale: str
    decidedBy: str
    decidedAt: str
    reviewSha: str
    adr: str


class ContextRef(TypedDict, total=False):
    """A bounded reference into the repo. A cache, never the source of truth."""

    path: str
    blobSha: str
    lines: list[list[int]]
    symbols: list[str]
    excerpt: str


class ContextCapsule(TypedDict, total=False):
    refs: list[ContextRef]
    interfaces: str
    conventions: str
    commands: dict[str, str]
    doNotTouch: list[str]
    budget: dict[str, int]


class TaskNode(TypedDict, total=False):
    id: str
    title: str
    #: Plain-language one-liner, <= 150 chars, generated by :mod:`adlc.summarize`.
    #: The task graph is the report's primary navigation, and a reader scanning
    #: it needs to know what a node does without opening it.
    tldr: str
    kind: TaskKind
    dependsOn: list[str]
    level: int
    writeSet: list[str]
    acceptance: list[str]
    rubricIds: list[str]
    adrRefs: list[str]
    context: ContextCapsule


class TaskGraph(TypedDict, total=False):
    runId: str
    baseSha: str
    specDigest: str
    nodes: list[TaskNode]


class TaskOutcome(TypedDict, total=False):
    status: Literal["ok", "fail", "skipped"]
    patchPath: str
    log: str
    tokensIn: int
    tokensOut: int
    cost: float


class RubricCriterion(TypedDict, total=False):
    id: str
    score: float
    weight: float
    passed: bool
    rationale: str
    evidence: list[str]


class RubricScore(TypedDict, total=False):
    overall: float
    threshold: float
    passed: bool
    criteria: list[RubricCriterion]


class Rubric(TypedDict, total=False):
    id: str
    threshold: float
    criteria: list[dict[str, Any]]


class FlagResult(TypedDict, total=False):
    key: str
    value: Any
    variant: str
    reason: str


# ---------------------------------------------------------------------------
# Human feedback  (mirrored by ``schemas/human-feedback-pack.schema.json``)
# ---------------------------------------------------------------------------

AnnotationShape = Literal["rect", "arrow", "highlight", "freehand", "point", "whole"]
CritiqueTargetKind = Literal["squad_finding", "persona", "rubric_criterion", "adr"]
CritiqueStance = Literal["agree", "disagree", "needs_evidence", "out_of_scope"]
DiffTargetKind = Literal["measurement", "screenshot", "coverage"]
FeedbackVerdict = Literal["accept", "reject", "revise"]
FeedbackRoute = Literal["outer", "inner"]
FeedbackSeverity = Literal["info", "minor", "major", "blocker"]

#: Hard caps applied when a pack is ingested. The pack is authored in a browser
#: and its rendered form is read by an agent in the successor run, so every free
#: text field is truncated rather than trusted.
FEEDBACK_MAX_TEXT = 4_000
FEEDBACK_MAX_ITEMS = 500

#: ``verdict`` -> the ``Decision.outcome`` it produces.
FEEDBACK_OUTCOME: dict[str, DecisionOutcome] = {
    "accept": "ship",
    "reject": "do_not_ship",
    "revise": "iterate",
}


class AnnotationGeometry(TypedDict, total=False):
    #: Normalised to the artifact's NATURAL size. Storing rendered pixels would
    #: make an annotation mean something different at a different viewport width.
    points: list[list[float]]


class Annotation(TypedDict, total=False):
    """Visual markup anchored to one evidence artifact by its SHA-256."""

    id: str
    artifactSha256: str
    artifactPath: str
    artifactKind: str
    shape: AnnotationShape
    geometry: AnnotationGeometry
    timestampMs: float | None
    severity: FeedbackSeverity
    comment: str
    requirementIds: list[str]


class Critique(TypedDict, total=False):
    """A judgement on agent-authored reasoning."""

    id: str
    targetKind: CritiqueTargetKind
    targetRef: str
    targetTitle: str
    #: ``sha256:`` of the exact reasoning text critiqued, so drift is detectable.
    sourceDigest: str
    stance: CritiqueStance
    severity: FeedbackSeverity
    comment: str


class DiffDecision(TypedDict, total=False):
    """Accept or reject one evidence-vs-baseline delta."""

    id: str
    targetKind: DiffTargetKind
    targetId: str
    decision: Literal["accept", "reject"]
    comment: str
    annotationIds: list[str]


class HumanFeedbackPack(TypedDict, total=False):
    """The ``adlc-human-feedback/v1`` document.

    Untrusted. Possession confers **no** authority: in CI a pack must arrive via
    a native PR review or ``workflow_dispatch``, both of which already require
    write permission.
    """

    schemaVersion: str
    runId: str
    candidateSha: str
    reportDigest: str
    packDigest: str
    submittedAt: str
    submittedBy: str
    verdict: FeedbackVerdict
    route: FeedbackRoute
    summary: str
    annotations: list[Annotation]
    critiques: list[Critique]
    diffDecisions: list[DiffDecision]


# ---------------------------------------------------------------------------
# Evidence diff  (mirrored by ``schemas/evidence-diff.schema.json``)
# ---------------------------------------------------------------------------


class MeasurementDelta(TypedDict, total=False):
    metricId: str
    change: Literal["added", "removed", "changed", "unchanged"]
    value: float | None
    baselineValue: float | None
    delta: float | None
    budget: float | None
    passed: bool | None
    baselinePassed: bool | None
    budgetCrossed: Literal["entered_breach", "left_breach", "none"]
    collector: str
    artifactSha256: str


class CoverageDelta(TypedDict, total=False):
    requirementId: str
    change: Literal["added", "removed", "gained", "lost", "unchanged"]
    present: bool | None
    baselinePresent: bool | None
    evidenceKinds: list[str]
    baselineEvidenceKinds: list[str]


class ScreenshotDelta(TypedDict, total=False):
    #: Relative to ``evidence/<variant>/`` so a variant rename does not read as a
    #: wholesale replacement of every screenshot.
    path: str
    change: Literal["added", "removed", "changed", "unchanged"]
    sha256: str | None
    baselineSha256: str | None
    bytes: int | None
    baselineBytes: int | None


class EvidenceDiff(TypedDict, total=False):
    schemaVersion: str
    runId: str
    baselineRunId: str | None
    reason: str
    generatedAt: str
    measurements: list[MeasurementDelta]
    coverage: list[CoverageDelta]
    screenshots: list[ScreenshotDelta]
    summary: dict[str, int]


class Run(TypedDict, total=False):
    """The canonical ``adlc-run/v1`` document.

    Only :func:`adlc.reduce.reduce_run` may write this. Stages never do -- that
    is what makes parallel GitHub Actions jobs safe.
    """

    schemaVersion: str
    runId: str
    createdAt: str
    referencesRun: str | None
    #: Which loop a successor run re-enters. ``outer`` re-specs from the brief;
    #: ``inner`` rebuilds against the existing spec. ``None`` for an original run.
    #: This is read by :func:`adlc.stages.feedback.retrigger_loop`, so it is a
    #: control value, not a label.
    route: str | None
    repo: str
    baseSha: str
    headSha: str
    prNumber: int | None
    status: RunStatus
    profile: Literal["minimal", "full"]
    capabilities: dict[str, str]
    stages: list[StageResult]
    variants: list[Variant]
    gates: list[GateResult]
    artifacts: list[ArtifactRef]
    decision: Decision | None
    experimentRef: str | None


# ---------------------------------------------------------------------------
# Protocols
# ---------------------------------------------------------------------------


@runtime_checkable
class Adapter(Protocol):
    """Base contract. Every adapter is discoverable and self-describing."""

    name: str
    kind: AdapterKind

    @staticmethod
    def detect(cfg: Config) -> tuple[bool, str]:
        """Return ``(available, reason)``.

        ``reason`` is surfaced verbatim in ``capabilities.json`` and in any
        ``not_run`` gate, so it must be human-readable and specific.
        """
        ...


@runtime_checkable
class AgentRunner(Adapter, Protocol):
    async def run_task(
        self, node: TaskNode, worktree: Path, cfg: Config
    ) -> TaskOutcome:
        """Execute one task node inside an isolated worktree.

        MUST produce a patch anchored to the worktree's base SHA and MUST NOT
        write outside ``node['writeSet']``.
        """
        ...


@runtime_checkable
class TaskStore(Adapter, Protocol):
    def sync(self, graph: TaskGraph) -> dict[str, str]:
        """Push the graph to the store. Returns ``{node_id: external_id}``."""
        ...

    def update(self, node_id: str, status: str, note: str = "") -> None: ...


@runtime_checkable
class EvalRunner(Adapter, Protocol):
    def run(self, run: Run, rubric: Rubric) -> RubricScore: ...


@runtime_checkable
class EvidenceCollector(Adapter, Protocol):
    def collect(self, run: Run, variant: str, out: Path) -> list[ArtifactRef]: ...


@runtime_checkable
class FlagProvider(Adapter, Protocol):
    def materialize(self, run: Run) -> Path:
        """Write the flag definition file (e.g. ``flags.flagd.json``)."""
        ...

    def evaluate(self, key: str, ctx: dict[str, Any]) -> FlagResult: ...


@runtime_checkable
class GateRunner(Adapter, Protocol):
    id: str
    required_by_default: bool

    def evaluate(self, run: Run, cfg: Config) -> GateResult: ...


@runtime_checkable
class Telemetry(Adapter, Protocol):
    def emit(self, span: dict[str, Any]) -> None:
        """Emit an OTel-shaped span.

        Feature-flag spans MUST use current semconv names:
        ``feature_flag.key``, ``feature_flag.provider.name``,
        ``feature_flag.result.variant``, ``feature_flag.result.reason``,
        ``feature_flag.context.id``, ``feature_flag.set.id``.
        """
        ...


@runtime_checkable
class Exporter(Adapter, Protocol):
    def export(self, run: Run, out: Path) -> Path: ...
