"""Deterministic ELI5 / TL;DR summaries, hard-capped at 150 characters.

Every navigable thing in the evidence report -- a task node, a gate, an ADR, an
evidence artifact, a persona walkthrough -- carries a one-line summary so a
reader can scan the graph without opening anything.

Three properties make these summaries trustworthy rather than decorative:

* **Deterministic and offline.** No model is involved. The same run always
  renders the same sentence, so a summary can be diffed across runs and can be
  regenerated by anyone from the same inputs.
* **Grounded.** Every clause is derived from a field that already exists
  (title, kind, write set, status, measured value). Nothing is invented. When
  there is nothing to say, that is said plainly rather than padded.
* **Bounded.** :data:`TLDR_LIMIT` is enforced by :func:`clamp`, which truncates
  on a word boundary. A summary that overflows its budget is a layout bug in a
  card that has to hold hundreds of them.

The vocabulary is deliberately plain: "Builds", "Proves", "Explains". The reader
of a task-graph node may be a product owner, not the engineer who wrote it.
"""

from __future__ import annotations

import re
from typing import Any

__all__ = [
    "TLDR_LIMIT",
    "adr_tldr",
    "artifact_tldr",
    "clamp",
    "compose",
    "gate_tldr",
    "humanise_bytes",
    "node_tldr",
    "persona_tldr",
    "requirement_tldr",
]

#: Hard cap for every summary in the report. Cards are laid out against it.
TLDR_LIMIT = 150

#: Ellipsis used when clamping. ASCII on purpose -- these strings are written
#: into JSON, echoed by the CLI, and read in Windows consoles that still
#: default to cp1252.
_ELLIPSIS = "..."

_KIND_VERB: dict[str, str] = {
    "implement": "Builds",
    "test": "Proves",
    "doc": "Explains",
    "infra": "Wires up",
}

_LEADING_VERB = re.compile(
    r"^\s*(?:add|adds|added|implement|implements|create|creates|build|builds|write|writes"
    r"|update|updates|introduce|introduces|make|makes|set\s+up|setup|wire|wires"
    r"|document|documents|test|tests|verify|verifies)\b\s*",
    re.IGNORECASE,
)
_ARTICLE = re.compile(r"^(?:a|an|the)\s+", re.IGNORECASE)
_WHITESPACE = re.compile(r"\s+")


def clamp(text: str, limit: int = TLDR_LIMIT) -> str:
    """Collapse whitespace and truncate ``text`` on a word boundary.

    Truncation happens at the last space before the budget so a summary never
    ends mid-word, which reads as corruption rather than as brevity.
    """
    collapsed = _WHITESPACE.sub(" ", str(text or "")).strip()
    if len(collapsed) <= limit:
        return collapsed
    room = max(1, limit - len(_ELLIPSIS))
    cut = collapsed[:room]
    if " " in cut[max(0, room - 30):]:
        cut = cut[: cut.rstrip().rfind(" ")]
    return cut.rstrip(" ,;:.-") + _ELLIPSIS


def compose(*clauses: str, limit: int = TLDR_LIMIT) -> str:
    """Join clauses in priority order, keeping only those that still fit.

    The first clause is the one that must survive, so it is clamped rather than
    dropped. Later clauses are context: valuable when there is room, never worth
    truncating the subject for.
    """
    parts = [_WHITESPACE.sub(" ", str(c or "")).strip().rstrip(".") for c in clauses]
    parts = [p for p in parts if p]
    if not parts:
        return ""
    out = clamp(parts[0] + ".", limit)
    for clause in parts[1:]:
        candidate = f"{out} {clause}."
        if len(candidate) <= limit:
            out = candidate
    return out


def humanise_bytes(size: Any) -> str:
    try:
        value = float(size)
    except (TypeError, ValueError):
        return "unknown size"
    for unit in ("B", "KB", "MB", "GB"):
        if value < 1024 or unit == "GB":
            return f"{value:.0f} {unit}" if unit == "B" else f"{value:.1f} {unit}"
        value /= 1024
    return f"{value:.1f} GB"


def _subject(title: str) -> str:
    """Strip a leading verb and article so the generated verb is not doubled."""
    text = _WHITESPACE.sub(" ", str(title or "")).strip().rstrip(".")
    text = _LEADING_VERB.sub("", text)
    text = _ARTICLE.sub("", text)
    if not text:
        return "this task"
    return text[0].lower() + text[1:] if text[:2] != text[:2].upper() else text


def _where(write_set: list[str] | None) -> str:
    paths = [p for p in (write_set or []) if p]
    if not paths:
        return ""
    first = paths[0]
    folder = first.rsplit("/", 1)[0] if "/" in first else first
    if len(paths) == 1:
        return f"Touches {first}"
    return f"Touches {len(paths)} files under {folder}"


def node_tldr(node: dict[str, Any], *, limit: int = TLDR_LIMIT) -> str:
    """One plain-language line for a task-graph node.

    Answers the three questions a reader of a graph actually has: what does this
    do, where does it land, and what had to finish first.
    """
    verb = _KIND_VERB.get(str(node.get("kind") or "implement"), "Builds")
    deps = [d for d in (node.get("dependsOn") or []) if d]
    if not deps:
        order = "Starts in the first wave"
    elif len(deps) == 1:
        order = f"Waits for {deps[0]}"
    else:
        order = f"Waits for {len(deps)} earlier tasks"
    acceptance = [a for a in (node.get("acceptance") or []) if a]
    proves = f"Proves {', '.join(acceptance[:2])}" if acceptance else ""
    return compose(
        f"{verb} {_subject(node.get('title', ''))}",
        _where(node.get("writeSet")),
        order,
        proves,
        limit=limit,
    )


def gate_tldr(gate: dict[str, Any], *, limit: int = TLDR_LIMIT) -> str:
    """One line for a gate result, leading with what it means for the merge."""
    status = str(gate.get("status") or "not_run")
    required = bool(gate.get("required"))
    lead = {
        ("pass", True): "Passed a check that must pass to merge",
        ("pass", False): "Passed an advisory check",
        ("fail", True): "Failed a check that must pass to merge",
        ("fail", False): "Failed an advisory check",
        ("not_run", True): "Never ran, and it had to -- that blocks the merge",
        ("not_run", False): "Never ran; it was optional",
    }.get((status, required), "Recorded a result")
    return compose(lead, str(gate.get("message") or ""), limit=limit)


def artifact_tldr(artifact: dict[str, Any], *, limit: int = TLDR_LIMIT) -> str:
    """One line for a captured artifact: what it is and what it can prove."""
    kind = str(artifact.get("kind") or "file")
    meaning = {
        "video": "A screen recording of the whole run -- watch what actually happened",
        "screenshot": "A still frame of the running app at one moment",
        "playwright_trace": "A step-by-step replayable trace of the browser session",
        "har": "Every network request the page made, with secrets stripped",
        "console_log": "Everything the page logged, with secrets stripped",
        "replay_script": "A script that reproduces this run on your own machine",
        "html_report": "A rendered report produced by a tool in the pipeline",
        "persona_feedback": "One persona's walkthrough, including what they were thinking",
        "json": "Structured measurements emitted by a collector",
        "jsonl": "A line-per-event record emitted by a collector",
    }.get(kind, f"A captured {kind.replace('_', ' ')} artifact")
    return compose(meaning, humanise_bytes(artifact.get("bytes")), limit=limit)


def adr_tldr(
    title: str, status: str, chosen: str = "", *, limit: int = TLDR_LIMIT
) -> str:
    """One line for a decision: what was decided and whether it is binding."""
    state = {
        "accepted": "Decided and in force",
        "rejected": "Considered and turned down",
        "proposed": "Proposed, not yet decided",
        "deprecated": "No longer in force",
        "superseded": "Replaced by a later decision",
    }.get(str(status or "").lower(), "Recorded")
    picked = f"Chose {_subject(chosen)}" if chosen and chosen != title else ""
    return compose(f"{state}: {_subject(title)}", picked, limit=limit)


def requirement_tldr(text: str, covered: bool, kinds: list[str] | None = None,
                     *, limit: int = TLDR_LIMIT) -> str:
    lead = "Backed by evidence" if covered else "No evidence attached yet"
    how = f"via {', '.join(kinds[:3])}" if covered and kinds else ""
    return compose(lead, how, _subject(text), limit=limit)


def persona_tldr(
    name: str, role: str, verdict: str, friction: int = 0, *,
    scenario: str = "", limit: int = TLDR_LIMIT
) -> str:
    """One line for a persona card.

    ``scenario`` is worth the characters it costs: a persona usually walks
    several scenarios, and without it every card in the report reads the same,
    which is worse than no summary because it looks like information.
    """
    outcome = {
        "satisfied": "got through the task",
        "blocked": "could not finish the task",
        "confused": "finished, but had to guess",
        "partial": "finished only part of the task",
    }.get(str(verdict or "").lower(), "walked the task")
    friction_clause = (
        f"Hit {friction} friction point{'s' if friction != 1 else ''}" if friction else ""
    )
    lead = f"{name}, a {role}, {outcome}"
    if scenario:
        lead = f"{lead} on {scenario}"
    return compose(lead, friction_clause, limit=limit)
